config/routes.rb
Rails.application.routes.draw do

  resources :products #, :except => [:create]
  resources :indis #, :except => [:create]
  as :indis do
    get 'indis/search' => 'indis#search'
  end
  get 'tasks/search'

  get "tasks/searchC"

  resources :profiles do
    resources :indis
    resources :products
  end
  #devise_for :users
  devise_for :users
  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  delete "indis/delete/:id/:file_id" =>  'indis#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

end

app/models/profile.rb
class GoodnessValidator < ActiveModel::Validator
  def validate(record)
    if record.country == "US" and record.state == " "
      record.errors[:base] << "State cannot be blank"
    end
    if record.country != "US" and record.state != " "
      record.errors[:base] << "Leave State empty for countries outside of United States..."
    end

  end
end

class Profile < ApplicationRecord
  has_many :indis, :dependent => :delete_all
  validates_with GoodnessValidator
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  #cache search criteria
  $last_company_search
  $last_state_search
  # GET /profiles
  # GET /profiles.json
  def index
    $last_company_search = "%#{params[:company]}%"
    $last_state_search = "%#{params[:state]}%"
    @profiles = if params[:company]
                  Profile.includes(:indis).where('company LIKE ? and state LIKE ?', "%#{params[:company]}%", "%#{params[:state]}%").order('company asc')
                else
               @profiles = Profile.all
                end
  end


  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        #format.html {redirect_to :controller => 'profiles', :company => $last_company_search, :state=> $last_state_search, notice: 'Company was successfully created.' }  CANNOT GET FLASH WORK!
        format.html {redirect_to @profile, :company => $last_company_search, :state=> $last_state_search, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to :controller => 'profiles', :company => $last_company_search, :state => $last_state_search, :flash => "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'profiles', :company => $last_company_search, :state => $last_state_search, notice: 'Company was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:company, :address1, :address2, :city, :state, :zip, :country, :website, :status, :referredby, :pobox)
    end
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :profile_company %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :profile_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :profile_address2 %>
  </div>

  <div class="field">
    <%= form.label :pobox %>
    <%= form.text_field :pobox, id: :profile_pobox %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :profile_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.collection_select(:state, State.select(:state_name, :state_code),
                               :state_code, :state_name)  %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :profile_zip %>
  </div>

  <div class="field">
  <%= form.label :country%>
    <%= form.country_select :country, priority_countries: ["US"], include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :profile_website %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :profile_status %>
  </div>

  <div class="field">
    <%= form.label :referredby %>
    <%= form.text_field :referredby, id: :profile_referredby %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', :back %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>
<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>

    <tr></tr>
      <tr></tr>
      <tr>
        <td><%= profile.company %></td>
        <td><%= profile.city %></td>
        <td><%= profile.state %></td>
        <td><%= link_to 'Show', profile %>
        <%= link_to 'Edit', edit_profile_path(profile) %>
        <%= link_to 'Delete', profile_path(id: profile.id), method: :delete, data: { confirm: 'Are you sure' } %>
        <%= link_to 'Products', profile_products_path(:profile_id => profile.id) %>
        <%= link_to 'New Contact', new_profile_indi_path(:profile_id => profile.id) %>
        </td>
        <td></td>
        <td></td>
        <td></td>

        <% profile.indis.each do | indi | %>
          <% s = indi.firstname.to_s + ' ' + indi.middle.to_s + ' ' + indi.lastname.to_s + ' ' + indi.contact_suffix.to_s %>
          <tr>
            <td>&nbsp&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspContact:</td>
            <td><%= s %></td>
            <td><%= %></td>
            <td><%= indi.jobtitle %></td>
            <td><%= indi.contact_email %></td>
            <td><%= link_to 'Show', indi %></td>
            <td><%= link_to 'Edit', edit_profile_indi_path(:id => indi.id, :profile_id => profile.id) %></td>
            <td><%= link_to 'Delete',  { controller: "indis", action: "destroy", id: indi.id },
                              method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
      <% end %>


    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_profile_path %>

<br>
<br>
<br>

<li >
  <%= link_to 'Back', 'tasks/search'%>
</li>

app/views/profiles/new.html.erb
 <h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', :back %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Showing Company</h1>
<p>
  <strong>Company:</strong>
  <%= @profile.company %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @profile.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @profile.address2 %>
</p>

<p>
  <strong>PO Box:</strong>
  <%= @profile.pobox %>
</p>


<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @profile.zip %>
</p>

<p>
  <strong>Country:</strong>
  <%= @profile.country %>
</p>


<p>
  <strong>Website:</strong>
  <%= @profile.website %>
</p>

<p>
  <strong>Status:</strong>
  <%= @profile.status %>
</p>

<p>
  <strong>Referredby:</strong>
  <%= @profile.referredby %>
</p>

<%= link_to "Back",   {controller: "profiles", action: "index", :company => $last_company_search, :state=> $last_state_search} %>