config/routes.rb
Rails.application.routes.draw do

  resources :products #, :except => [:create]
  resources :indis #, :except => [:create]
  as :indis do
    get 'indis/search' => 'indis#search'
  end
  get 'tasks/search'

  get "tasks/searchC"

  resources :profiles do
    resources :indis
    resources :products
  end
  #devise_for :users
  devise_for :users
  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  delete "indis/delete/:id/:file_id" =>  'indis#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

end

app/models/indi.rb
class Indi < ApplicationRecord
  belongs_to :profile, foreign_key: :profile_id
  has_many_attached :files
end

app/models/profile.rb
class GoodnessValidator < ActiveModel::Validator
  def validate(record)
    if record.country == "US" and record.state == " "
      record.errors[:base] << "State cannot be blank"
    end
    if record.country != "US" and record.state != " "
      record.errors[:base] << "Leave State empty for countries outside of United States..."
    end

  end
end

class Profile < ApplicationRecord
  has_many :indis, :dependent => :delete_all
  validates_with GoodnessValidator
end

app/controllers/indis_controller.rb
class IndisController < ApplicationController
  before_action :set_indi, only: [:show, :edit, :update, :destroy]

  # GET /indis
  # GET /indis.json
  #
  # cache parameters
  $last
  $first

  def index
  # cache parameters
    $last= "%#{params[:lastname]}%"
    $first = "%#{params[:firstname]}%"
    @indis = if params[:lastname] && params[:firstname]
               Indi.joins("INNER JOIN profiles ON profiles.id = profile_id").where(  'lastname LIKE ? and firstname LIKE ?', "%#{params[:lastname]}%", "%#{params[:firstname]}%" ).order('company asc')
             else
               @indis = Indi.all
             end
  end

  def search
    @indis = Indi.all
  end

  # GET /indis/1
  # GET /indis/1.json
  def show
  end

  # GET /indis/new
  def new
    @indi = Indi.new
  end
  # GET /indis/1/edit
  def edit
  end

  # POST /indis
  # POST /indis.json
  def create
    @indi = Indi.new(indi_params)
    respond_to do |format|
      if @indi.save
        if $horrible_global
          format.html { redirect_to :controller => 'profiles', :company => $last_company_search, :state => $last_state_search, :action => 'index', notice: 'Contact successfully updated.' }
        else
          format.html { redirect_to :controller => 'indis', :action => 'index', :lastname => $last, :firstname => $first, notice: 'Contact successfully updated.' }
        end
      else
        format.html { render :new }
        format.json { render json: @indi.errors, status: :unprocessable_entity }
        puts(@indi.errors.inspect)
      end
    end
  end

  # PATCH/PUT /indis/1
  # PATCH/PUT /indis/1.json
  def update            #YOU MUST SUPPLY A RESPONSE IN HTML OR YOUR API WILL BREAK
    respond_to do |format|
      if @indi.update(indi_params)
        if $horrible_global
          format.html { redirect_to :controller => 'profiles', :company => $last_company_search, :state => $last_state_search, :action => 'index', notice: "Contact successfully updated." }
        else
          format.html { redirect_to :controller => 'indis', :action => 'index', :lastname => $last, :firstname => $first, notice: 'Contact successfully updated.' }
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /indis/1
  # DELETE /indis/1.json
  def destroy
# if you start getting nil class errors it probably means the list of attachments hasn't been refreshed and are stale!
# when it says purge is not a method on nil it doesn't mean purge is not a method on file, it's just that there is no file object!
# handle selective purge
    if params[:file_id]
      @indi.files.find_by_id(params[:file_id]).purge
      respond_to do |format|
          format.html { render :show, notice: 'Contact successfully updated.' }
      end
# when it says purge is not a method on nil it doesn't mean purge is not a method on file, it's just that there is no file object!

# handle purge all.  this is not implemented yet.
    else

    @indi.destroy
              respond_to do |format|
                if $horrible_global#coming from companies list
                  format.html { redirect_to :controller => 'profiles', :company => $last_company_search, :state => $last_state_search, notice: 'Contact was successfully deleted.' }
                else
                  format.html { redirect_to :controller => 'indis', :action => 'index', :lastname => $last, :firstname => $first, notice: 'Contact was successfully deleted.' }
                end
                format.json { head :no_content }
              end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indi
      @indi = Indi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indi_params
      params.require(:indi).permit(:greet, :firstname, :middle, :lastname,  :workphone, :extension, :mobilephone,:profile_id, :contact_email, :contact_suffix, :jobtitle, :department, :remarks, files: [])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  #cache search criteria
  $last_company_search
  $last_state_search
  # GET /profiles
  # GET /profiles.json
  def index
    $last_company_search = "%#{params[:company]}%"
    $last_state_search = "%#{params[:state]}%"
    @profiles = if params[:company]
                  Profile.includes(:indis).where('company LIKE ? and state LIKE ?', "%#{params[:company]}%", "%#{params[:state]}%").order('company asc')
                else
               @profiles = Profile.all
                end
  end


  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        #format.html {redirect_to :controller => 'profiles', :company => $last_company_search, :state=> $last_state_search, notice: 'Company was successfully created.' }  CANNOT GET FLASH WORK!
        format.html {redirect_to @profile, :company => $last_company_search, :state=> $last_state_search, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to :controller => 'profiles', :company => $last_company_search, :state => $last_state_search, :flash => "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'profiles', :company => $last_company_search, :state => $last_state_search, notice: 'Company was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:company, :address1, :address2, :city, :state, :zip, :country, :website, :status, :referredby, :pobox)
    end
end

app/views/profiles/indis/_form.html.erb
<%= form_with(model: indi, local: true) do |form| %>
  <% if indi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(indi.errors.count, "error") %> prohibited this indi from being saved:</h2>

      <ul>
      <% indi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :greet %>
    <%= form.text_field :greet, id: :indi_greet %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :indi_firstname %>
  </div>

  <div class="field">
    <%= form.label :middle %>
    <%= form.text_field :middle, id: :indi_middle %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :indi_lastname %>
  </div>

  <div class="field">
    <%= form.label :suffix %>
    <%= form.text_field :contact_suffix, id: :indi_contact_suffix %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :contact_email, id: :indi_contact_email %>
  </div>

  <div class="field">
    <%= form.label :jobtitle %>
    <%= form.text_field :jobtitle, id: :indi_jobtitle %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department, id: :indi_department %>
  </div>

  <div class="field">
    <%= form.label "Work Phone"%>
    <%= form.text_field :workphone, id: :indi_workphone %>
  </div>
  <div class="field">
    <%= form.label :extension %>
    <%= form.text_field :extension, id: :indi_extension %>
  </div>
  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobilephone, id: :indi_mobilephone %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks, id: :indi_remarks, size: "80x7"%>
  </div>
  <%= form.file_field :files, multiple: true, direct_upload: true %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/indis/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', indi: @indi %>


<% if $horrible_global == true %>
  <%= link_to "Back",   :back %>
<% else %>
  <%= link_to "Back",   :back %>
<% end %>

app/views/profiles/indis/index.html.erb
<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
      <th>Job Title</th>
      <th>Email</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indis.each do |indi| %>
    <% s = indi.firstname.to_s + ' ' + indi.middle.to_s + ' ' + indi.lastname.to_s + ' ' + indi.contact_suffix.to_s %>
    <tr>
        <td><%= s %></td>
        <td><%= %></td>
        <td><%= %></td>
        <td><%= %></td>
        <td><%= indi.jobtitle %></td>
        <td><%= indi.contact_email %></td>
        <td><%= indi.profile.company %></td>

        <td><%= link_to 'Show', indi %></td>
        <td><%= link_to 'Edit', edit_indi_path(indi) %></td>
        <td><%= link_to 'Delete',  { controller: "indis", action: "destroy", id: indi.id },
                          method: :delete, data: { confirm: "Are you sure?" } %></td>
        <td><%= link_to 'New Contact', new_profile_indi_path(:profile_id => indi.profile.id) %></td>
      </tr>
     <% end %>
  </tbody>
</table>

<br>


<br>
<br>
<br>
<li >
  <%= link_to 'Back', root_path %>
</li>

app/views/profiles/indis/new.html.erb
<h1>New Contact</h1>

<% if $horrible_global == true
     puts("horrible is true so do companies") %>
  <%= link_to "Back",   :back %>
<% else %>
  <%= link_to "Back",   :back %>
<% end %>

<P></P>
<%= form_for(@indi, url: {controller: "indis", action: "create"}, method: "post") do |form| %>

  <div class="field">
    <%= form.hidden_field :profile_id, {  :value => params[:profile_id]} %>
  </div>

  <div class="field">
    <%= form.label :greet %>
    <%= form.text_field :greet, id: :indi_greet %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :indi_firstname %>
  </div>

  <div class="field">
    <%= form.label :middle %>
    <%= form.text_field :middle, id: :indi_middle %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :indi_lastname %>
  </div>

  <div class="field">
    <%= form.label :suffix %>
    <%= form.text_field :contact_suffix, id: :indi_contact_suffix %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :contact_email, id: :indi_contact_email %>
  </div>

  <div class="field">
    <%= form.label :jobtitle %>
    <%= form.text_field :jobtitle, id: :indi_jobtitle %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department, id: :indi_department %>
  </div>

  <div class="field">
    <%= form.label "Work Phone" %>
    <%= form.text_field :workphone, id: :indi_workphone %>
  </div>
  <div class="field">
    <%= form.label :extension %>
    <%= form.text_field :extension, id: :indi_extension %>
  </div>
  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobilephone, id: :indi_mobilephone %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks, id: :indi_remarks, size: "80x7"%>
  </div>


  <P></P>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/indis/show.html.erb
<h1>Showing Contact</h1>

<p>
  <strong>Greet:</strong>
  <%= @indi.greet %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @indi.firstname %>
</p>

<p>
  <strong>Middle:</strong>
  <%= @indi.middle %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @indi.lastname %>
</p>

<p>
  <strong>Suffix:</strong>
  <%= @indi.contact_suffix %>
</p>

<p>
  <strong>Email:</strong>
  <%= @indi.contact_email %>
</p>

<p>
  <strong>Jobtitle:</strong>
  <%= @indi.jobtitle %>
</p>

<p>
  <strong>Department:</strong>
  <%= @indi.department %>
</p>

<p>
  <strong>Work Phone:</strong>
  <%= @indi.workphone %>
</p>
<p>
  <strong>Extension:</strong>
  <%= @indi.extension %>
</p>
<p>
  <strong>Mobile:</strong>
  <%= @indi.mobilephone %>
</p>
<p>
  <strong>Remarks:</strong>
  <%= @indi.remarks %>
</p>
<p>

  <% @indi.files.each do |file| %>
    <%= link_to file.filename, file %>
    <%# somehow it passes the id of the right person, it looks like we only pass file_id doesn't it but it knows which person/contact/indi %>
    <%= link_to 'Delete', { controller: "indis", action: "destroy", file_id: file.id }, method: :delete, data: { confirm: "Are you sure?" }, style: 'color:#FF0000' %>
<% end %>

</p>

<% if $horrible_global == true %>
     <%= link_to "Back",   {controller: "profiles", action: "index", :company => $last_company_search, :state=> $last_state_search} %>
  <% else %>
     <%= link_to "Back",   {controller: "indis", action: "index", :lastname => $last, :firstname => $first}  %>
<% end %>