config/routes.rb
Rails.application.routes.draw do

  resources :products #, :except => [:create]
  resources :indis #, :except => [:create]
  as :indis do
    get 'indis/search' => 'indis#search'
  end
  get 'tasks/search'

  get "tasks/searchC"

  resources :profiles do
    resources :indis
    resources :products
  end
  #devise_for :users
  devise_for :users
  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  delete "indis/delete/:id/:file_id" =>  'indis#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :profile, foreign_key: :profile_id
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
   # @products = Product.where("profile_id = ?", "%#{params[:profile_id]}%")
    @products = Product.where("profile_id = ?", params[:profile_id])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    puts(product_params)
    puts(@product.internal_code)
    puts(@product.detail)
    puts(@product.pic)
    puts(@product.profile_id)
    respond_to do |format|
      if @product.save
#        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.html { redirect_to :controller => 'products', :profile_id => @product.profile_id, :action => 'index', notice: 'Product successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        puts(@product.errors.full_messages)
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to :controller => 'products', :profile_id => @product.profile_id, :action => 'index', notice: 'Product successfully updated.' }
        format.json { render :show,  status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'products', notice: 'Product was successfully deleted.' }
      #format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:internal_code, :detail, :pic, :profile_id)
    end
end

app/views/products/_form.html.erb
<%= form_with( model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this indi from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :profile_id, {  :value => params[:profile_id]} %>
  </div>

  <div class="field">
    <%= form.label :resin %>
    <%= form.collection_select(:internal_code, Resin.select(:product_code),
                               :product_code, :product_code)  %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <% somevalue = params[:profile_id] %>
  <% puts(somevalue) %>

  <div class="field">
    <%= form.label "Person in Charge" %>
    <%= form.collection_select(:pic, Indi.select(:lastname).where("profile_id = ?", somevalue),
                               :lastname, :lastname)  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>


<%= link_to "Back",   {controller: "products", action: "index"} %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<% puts(params[:profile_id])%>
<% companyRecord = Profile.find( params[:profile_id])%>

<h1>Products for <%= companyRecord.company %></h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Detail</th>
      <th>Person In Charge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.internal_code %></td>
        <td><%= product.detail %></td>
        <td><%= product.pic %></td>
        <td><%= link_to 'Show', profile_product_path(:id => product.id, :profile_id => params[:profile_id]) %></td>
        <td><%= link_to 'Edit', edit_profile_product_path(:id => product.id, :profile_id => params[:profile_id]) %></td>
        <td><%= link_to 'Delete',  { controller: "products", action: "destroy", id: product.id },
                        method: :delete, data: { confirm: "Are you sure?" } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_profile_product_path(:profile_id => params[:profile_id]) %>
<%= link_to "Back",   {controller: "profiles", action: "index", :company => $last_company_search, :state=> $last_state_search} %>

app/views/products/new.html.erb
<h1>New Product</h1>



<%= render 'form', product: @product %>
<%= link_to "Back",   {controller: "products", action: "index"} %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resin:</strong>
  <%= @product.internal_code %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @product.detail %>
</p>

<p>
  <strong>Person in Charge:</strong>
  <%= @product.pic %>
</p>
<% puts(params[:profile_id])%>
<%= link_to 'Edit', edit_profile_product_path(@product, :profile_id => params[:profile_id]) %> |
<%= link_to "Back",   {controller: "products", action: "index"} %>